version: '3.9'

services:
  # node_app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    restart: always

volumes:
  pgdata:
